AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Face detection AWS stack to discover a unique 'fingerprint' of a face and find it in public photo albums

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  PetStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: community.flock.facedetection.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/face-detection-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 1512
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonRekognitionFullAccess
        - AmazonS3ReadOnlyAccess
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets'
    Export:
      Name: SpringBootPetStoreFallbackApi
